#include <iostream>
#include <vector>
#include <random>
#include <cstdlib>
#include <time.h>

using namespace std;

void sortArray(vector<int> &a);
void quicksort(vector<int> &a, int l, int r);
void quicksort(vector<int> &a, int l, int r);
vector<int> partition(vector<int> &a, int l, int r);
int choosePivot(int l, int r);

int main()
{
    int n;
    cin >> n;

    vector<int> a(n);

    for (int i = 0; i < n; i++)
    {
        cin >> a[i];
    }

    sortArray(a);

    for (int i = 0; i < n; i++)
    {
        cout << a[i] << " ";
    }

    return 0;
}

void sortArray(vector<int> &a)
{
    quicksort(a, 0, a.size() - 1);
}
void quicksort(vector<int> &a, int l, int r)
{

    if (l >= r)
    {
        return;
    }

    int i = choosePivot(l, r);
    swap(a[l], a[i]);
    vector<int> p = partition(a, l, r);

    quicksort(a, l, p[0]);
    quicksort(a, p[1], r);
}
void swap(int &a, int &b)
{
    int temp = a;
    a = b;
    b = temp;
}

vector<int> partition(vector<int> &a, int l, int r)
{

    int i = l;
    int pivot = a[l];

    int s = l;

    for (int i = l + 1; i <= r; i++)
    {
        if (a[i] < pivot)
        {
            s += 1;
            swap(a[i], a[s]);
        }
    }

    swap(a[l], a[s]);

    int e = s;

    for (int i = s + 1; i <= r; i++)
    {
        if (a[i] == pivot)
        {
            e += 1;
            swap(a[i], a[e]);
        }
    }

    vector<int> res(2);
    res[0] = s - 1;
    res[1] = e + 1;

    return res;
}
int choosePivot(int l, int r)
{
    static random_device rd;
    //applying random seed, starting point to generate numbers
    //if seed same numbers generated are same
    //mt19937 is Mersenne Twister, generates very large random numbers

    static mt19937 gen(rd());
    //static so that seeding happens only once

    uniform_int_distribution<int> dist(l, r);

    //this transforms very large number generated by Mersenne Twister to l to r
    int randomNumber = dist(gen);
    return randomNumber;
}

int choosePivotV2(int l, int r)
{
    static bool isSeedDone = false;
    static random_device rd;

    //header <cstdlib> for rand and srand
    //header <time.h> for time
    if (!isSeedDone)
    {
        //seeding rand
        srand(rd());

        //if you need to seed fast use
        //srand(time(0))
        isSeedDone = true;
    }

    int n = r - l + 1;

    //another way but rand()%n is not as uniform as your previous
    int pivot = (rand() % n) + l;
    return pivot;
}